# Generated by Django 2.1.7 on 2019-03-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='用户名')),
                ('phone', models.CharField(max_length=255, verbose_name='手机号码')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='班次名')),
                ('start_time', models.DateTimeField(verbose_name='开启时间')),
                ('message', models.CharField(max_length=255, verbose_name='发送信息')),
                ('result', models.BooleanField(default=True, verbose_name='结果')),
                ('description', models.CharField(max_length=10000, verbose_name='详细信息')),
            ],
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='班次名')),
                ('start_hour', models.IntegerField(verbose_name='开始时间')),
                ('start_minute', models.IntegerField(verbose_name='开始时间')),
                ('start_message', models.CharField(max_length=255, verbose_name='开始发送信息')),
                ('end_hour', models.IntegerField(verbose_name='结束时间')),
                ('end_minute', models.IntegerField(verbose_name='结束时间')),
                ('end_message', models.CharField(max_length=255, verbose_name='结束发送信息')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='message',
            field=models.CharField(max_length=255, verbose_name='发送信息'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=255, verbose_name='班次名'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(verbose_name='开启时间'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='exec_date',
            field=models.CharField(max_length=255, verbose_name='执行日期'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='message',
            field=models.CharField(max_length=255, verbose_name='发送信息'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=255, verbose_name='班次名'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift',
            field=models.CharField(choices=[('O', 'Once'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=4, verbose_name='班次类型'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_hour',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
    ]
